- hosts: all
  tasks:
          - name: install req
            apt: name={{ item }} state=latest update_cache=yes
            loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

          - name: add docker key
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
                    state: present

          - name: add docker repo
            apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present

          - name: update apt and install docker
            apt: update_cache=yes name=docker-ce state=latest

          - name: install python docker module
            pip:
                    name: docker

          - name: node exporter
            shell: docker run -d --net="host" --pid="host" -v "/:/host:ro,rslave" quay.io/prometheus/node-exporter --path.rootfs=/host
